print("")
print("           |      |      |  ")  
print("          | |    | |    | |  ")
print("          | |    | |    | |  ")                   
print("          | |    | |    | |  ")                  
print("         --------------------")
print("         |                  |")
print("         |  HAPPY BIRTHDAY  |")
print("         |     SAUMYA!!     |")
print("          ===================")         
print("         |                  |")
print("         |                  |")
print("         |                  |")
print("         --------------------")
